-- 1. Habilitar la extensión de Vectores (Necesario para la IA)
create extension if not exists vector;

-- 2. Crear tabla de Conocimiento (Donde la IA busca respuestas)
create table if not exists public.vrp_knowledge (
  id bigint generated by default as identity primary key,
  content text,
  metadata jsonb,
  embedding vector(1536)
);

-- 3. Habilitar RLS en vrp_knowledge
alter table public.vrp_knowledge enable row level security;

-- 4. Políticas RLS para vrp_knowledge (solo admins)
create policy "Admin can manage vrp_knowledge" on public.vrp_knowledge
  for all using (is_admin()) with check (is_admin());

-- 5. Función de Búsqueda Semántica
create or replace function public.match_knowledge (
  query_embedding vector(1536),
  match_threshold float,
  match_count int
)
returns table (
  id bigint,
  content text,
  similarity float
)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  select
    vrp_knowledge.id,
    vrp_knowledge.content,
    1 - (vrp_knowledge.embedding <=> query_embedding) as similarity
  from vrp_knowledge
  where 1 - (vrp_knowledge.embedding <=> query_embedding) > match_threshold
  order by similarity desc
  limit match_count;
end;
$$;

-- 6. Crear tabla de Chat Events para historial
create table if not exists public.chat_events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  contact_id text not null,
  platform text not null,
  sender text not null,
  message text,
  meta jsonb
);

-- 7. Habilitar RLS en chat_events
alter table public.chat_events enable row level security;

-- 8. Políticas RLS para chat_events
create policy "Admin can manage chat_events" on public.chat_events
  for all using (is_admin()) with check (is_admin());

-- 9. Habilitar realtime para chat_events
alter publication supabase_realtime add table public.chat_events;

-- 10. Índice para búsqueda vectorial eficiente
create index if not exists vrp_knowledge_embedding_idx on public.vrp_knowledge 
  using ivfflat (embedding vector_cosine_ops) with (lists = 100);